### ISSUE TITLE
Add Autocomplete for "Tags" field

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/ore-ero#1012]
Add an autocomplete that loads the same data as the Tag Search box to the Tags field to avoid typos and case changes in Tags, as well as allow more visibility into Tags users may want to use.

**Comment by nschonni** [comment]
This might work https://wet-boew.github.io/wet-boew/demos/datalist/datalist-dynamic-en.html with a JSON file generated for the values on build
