### ISSUE TITLE
Add CI tests

### ISSUE THREAD

**Issue by gcharest** [canada-ca/ore-ero#102]
Need to add automated build tests such as:
* URL checks
* Dictionary
* Markdown roles

**Comment by imadeDev** [comment]
> Need to add automated build tests such as:
> 
> * URL checks
> * Dictionary
> * Markdown roles

> * URL checks:
 we already use html proofer:  the html-proofer gem lets you build and then test links on the built site, both external and internal, https://github.com/gjtorikian/html-proofer

**Comment by imadeDev** [comment]
- URL checks: 
We use html proofer:  the html-proofer gem lets you build and then test links on the built site, both external and internal, https://github.com/gjtorikian/html-proofer

**Comment by gcharest** [comment]
I meant in the repo for CITravis

Le jeu. 14 mars 2019 13 h 51, Imade Zarrari <notifications@github.com> a
écrit :
