### ISSUE TITLE
Code Form - Save updated data

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#109]
Related to #108

If data for a project was updated in the form, create a branch and push it to Github

**Comment by j-rewerts** [comment]
There's a few directions we can go here. I think the roadblock right now is how to get the code from a repo submitted to the upstream as a pull request. Basic Git functionality is provided by [Isomorphic Git](https://isomorphic-git.org/). 

To manage the PR, we could submit it anonymously using something like [GitMask](https://www.gitmask.com/) or [PRBot](https://github.com/PRB0t/PRB0t). GitMask doesn't require a GitHub token, which would be nicer to work with. Both are open source, so we can self host if that is a concern for us.

@BassamAjam Do you want me to take a whack at this?

**Comment by BassamAjam** [comment]
Great! GitMask is a good idea. And yes we can work together on this task.

**Comment by smellems** [comment]
Gitmask looks interesting.  Although, it would be good to know who is contributing pull requests so someone can validate the data being submitted (contact email, ..).

**Comment by j-rewerts** [comment]
@smellems Yeah good idea. We can add the submitter as the commit author, then either GitMask or PRBot will handle the PR.

I've tracked the issues upstream, as neither of those libraries allow us to specify the commit authors. [GitMask](https://github.com/AnalogJ/gitmask/issues/46). [PRBot](https://github.com/PRB0t/PRB0t/issues/38).  I'm thinking PRBot will probably be the way to go. The whole purpose of GitMask is anonymity, whereas PRBot is really exactly what we need.

In addition to the commit author, we could set their email in the commit message or the PR message.

**Comment by M3kH** [comment]
Hi @j-rewerts you can specify commit authors with PRB0t, but you would always need to use the OAuthToken that you want the user accredited for.
There is no possibility to do it in different way with GitHub apis.

Alternative you can look at [`Co-authored-by`](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) option that is available in GitHub, and you can give credit to users trough the commit description.

**Comment by j-rewerts** [comment]
@M3kH I've managed to find a way! I'll submit as a PR to PRB0t today. 

Closing, as it was resolved in #139.
