### ISSUE TITLE
Add YAML validation to build - Code

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#113]
Create a schema and enable build validation of YAML files of the Open Source Code section

**Comment by j-rewerts** [comment]
I'm hoping to start a discussion about how we'll document our YAML specification. 

It seems like most people use JSON Schema to define and validate their YAML.
 - [Blog post](https://medium.com/trabe/application-config-with-yaml-and-json-schema-validation-94a870855314) about YAML validation using JSON Schema
 - [JSON Schema site](http://json-schema.org/)

**Comment by j-rewerts** [comment]
Having this will be very important once we finish #109 , as it'll make reviewing the PRs that generates much easier.

**Comment by j-rewerts** [comment]
Another neat thing to think about is we could potentially build the forms for editing these files based on our schema. This would make it easy to reproduce the work we're doing in #109 for any other YAML file we want people to be able to edit.

**Comment by smellems** [comment]
@j-rewerts I really like this idea and we discussed it in the beginning.  We are reusing the same translations for both the metadata definition page and the form, but having everything generated based on a Schema would be the best solution.  Could the Schema definition contain names and descriptions of fields?

**Comment by smellems** [comment]
@imadeDev has started working on add YAML validation to the build in #117 using Yamale.  It seems to work nicely with our current build setup to define a simple schema that validates mandatory fields.

I think the goal of #102 would be to also reorganize the build.  Perhaps upgrading schema validation could be part of that.  I would like to be able to run `npm test` to run all test locally and for Travis
