### ISSUE TITLE
Clicking software names shows modal of JSON

### ISSUE THREAD

**Issue by nschonni** [canada-ca/ore-ero#12]
On https://canada-ca.github.io/ore-ero/open-source-software.html if you click the Drupal link to open  the project details, the modal opens with wrap JSON in the body like so
![Drupal Modal with JSON string](https://user-images.githubusercontent.com/1297909/36401331-df954452-15a4-11e8-8211-9da3239e675a.png)

This also happens with the Notepad++ links, so it might just be an issue with the template

**Comment by smellems** [comment]
Yes I did that as examples and to see what data was available for each OSS.  I updated the [open source code](https://canada-ca.github.io/ore-ero/open-source-code.html) modal to display readable things, but not yet for OSS section

**Comment by smellems** [comment]
This was done!
