### ISSUE TITLE
Mandatory contact - Validation

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#120]
We had defined the Contact Email to be the only mandatory Contact field.  But some of the data only has a link to the code/project's Issue tracker.  When adding YAML validation in #119 we had to make the Contact Email not mandatory or the build would be failing.

The goal is to have a way to contact the project.  The issue tracker does that, if someone is there to answer.  So that seem OK.  It also mean that we could add projects even if we can't find an email contact right away.  But I would still like to encourage emails as a more direct point of contact.

Can Yamle handle mandatory Email **or** URL?

**Comment by imadeDev** [comment]
in my opinion I encourage you to use an email as a direct point of contact and as a mandatory field

**Comment by j-rewerts** [comment]
Yeah agreed. Conditionally validating fields could get out of hand too. Between this and #121, it makes me wonder if we should have a policy about removing old projects?

**Comment by imadeDev** [comment]
in the file administrations / federal.yaml we can add the email of each organization or ministry, and use them as contact email in yaml files

**Comment by smellems** [comment]
Agreed!  Let's set the build validation for mandatory contact email.  The build will fail, I will look at fixing it by finding email or removing projects.

@imadeDev peux-tu faire les changements?

**Comment by imadeDev** [comment]
> Agreed! Let's set the build validation for mandatory contact email. The build will fail, I will look at fixing it by finding email or removing projects.
> 
> @imadeDev peux-tu faire les changements?

ok je vais faire les changements
