### ISSUE TITLE
Navigation causes `.svg` download

### ISSUE THREAD

**Issue by s-laugh** [canada-ca/ore-ero#1287]
Navigating to https://code.open.canada.ca/en/index.html causes a `wmms-blk.svg` to be downloaded to the computers downloads folder. This probably shouldn't happen.

I was using Edge.

**Comment by nschonni** [comment]
Thanks, I think it's probably related to https://github.com/wet-boew/cdts-sgdc/issues/176
That said, should probably try bumping up to a newer CDTS version to see if that resolves it

**Comment by s-laugh** [comment]
Looks like updating CDTS to the latest version will work.  
Fixed by #1294

**Comment by nschonni** [comment]
Landed #1294 and it seems to be better now
