### ISSUE TITLE
Replace Tables with Grid of Cards

### ISSUE THREAD

**Issue by s-laugh** [canada-ca/ore-ero#1316]
Tables aren't intuitively easy to read information from, so I want to propose a design change to using a Grid of Cards.
The design still uses the `table` element in the back end, so the filtering still functions exactly the same.

It primarily would use `.tbl-gridify` built into wet, and would require a small amount of custom styling.

_The design actually comes from the WET-BOEW styleguid https://wet-boew.github.io/wet-boew-styleguide/index-en.html (they are using a table element)_

![image](https://user-images.githubusercontent.com/22419216/102515987-5e686180-405c-11eb-95f3-2e762dcd0c9a.png)

**Comment by nschonni** [comment]
I'm OK with that if you want to give it a try.
Think you're write about the style tweaks, since I think the contrast is low on some of the text in the pic
