### ISSUE TITLE
create a form for open source software

### ISSUE THREAD

**Issue by BassamAjam** [canada-ca/ore-ero#137]
Create a new page with a form with all field from the open source software metadata schema
https://canada-ca.github.io/ore-ero/en/open-source-software-schema.html

Add validation for mandatory fields and data types.

**Comment by j-rewerts** [comment]
@BassamAjam Are you trying to dynamically build the form from the schema?

**Comment by BassamAjam** [comment]
I'm just doing the same thing as codeForm.html in the _includes folder

**Comment by smellems** [comment]
Just to note that for Software it might be a good idea to still have the form based on you Administration.  Even if the files are by software..

So you could be editing all the OSS for a city all at the same time and not have to update each software individually.

**Comment by j-rewerts** [comment]
I've been looking into this common problem identified, and I think I may have an idea for a test. Netlify is basically a CMS for flat-file statically generated sites. It allows you to authenticate with a GitHub account and do all of the things we're trying to do on our own, such as filling out forms to edit content. The big thing missing from it is it doesn't allow anonymous contributions, but we may be able to build that in.

**Comment by nschonni** [comment]
FYI, I looked at this a  long time ago for WET https://github.com/prose/prose, but that is for use with Jekyll sites

**Comment by j-rewerts** [comment]
One thing I really like about Netlify VS Prose is Netlify has a document schema framework built in. Prose presents it more as just editing files directly in my experience. I'll try to get an example of this to show here.
