### ISSUE TITLE
Language References GoC 

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/ore-ero#16]
All the language on the Open Resource Exchange references only Government of Canada Open Source projects yet the Open Source Code list includes municipal and provincial governments OS Projects. 

I get what you are going for but I think the language should reflect that this is not just for Government of Canada repos but for all governments within Canada.

**Comment by smellems** [comment]
It started out being just for GC but then we expanded it to include all Canadian public administrations: federal, provincial and municipal.  Including demo data.
