### ISSUE TITLE
Add additional fields by submitting the osc form

### ISSUE THREAD

**Issue by BassamAjam** [canada-ca/ore-ero#160]
The open source code form only works for the mandatory fields. We can also add the optional fields.

**Comment by j-rewerts** [comment]
I'm not 💯 on the best way to do this. I'm using Javascript string templating to build the string, but I'm starting to think this is a bad idea. See [here](https://github.com/canada-ca/ore-ero/blob/master/assets/js/src/index.js#L13). 

We could also just build the object, then convert to a YAML string on write. I might make this change while doing this issue.
