### ISSUE TITLE
Display a message after submitting the osc form.

### ISSUE THREAD

**Issue by BassamAjam** [canada-ca/ore-ero#167]
We can display a message in a popup that says the pull request is done correctly.
And we may add a message when the submission is failed.

**Comment by smellems** [comment]
Yes this would be good!  Can we also include a link to the pull request created?

**Comment by j-rewerts** [comment]
@WJXHenry Think you can handle this one?

**Comment by j-rewerts** [comment]
@BassamAjam Have you started work on this yet?

**Comment by WJXHenry** [comment]
If no one has started work on it, I'll be happy to take it on

**Comment by BassamAjam** [comment]
@j-rewerts  @WJXHenry Hello, I haven't started this task yet

**Comment by WJXHenry** [comment]
Cool, I'll start working on this!
