### ISSUE TITLE
Form submission not working

### ISSUE THREAD

**Issue by jethiercrc** [canada-ca/ore-ero#1688]
Greetings,

I've tried submitting an Open Source Code Form to https://code.open.canada.ca/en/open-source-code-form.html and the submission provides me with an orange symbol near the bottom of the page saying the "form is being submitted" but after 20+ minutes of waiting, nothing happens and I have not received any emails about the submission being successful.

I tried using both Edge and Chrome with no success. I'm currently using a GC laptop on a GC network (ISED).

Please advise.

Thanks,
-Jon

**Comment by nschonni** [comment]
Likely related to #1600

**Comment by jethiercrc** [comment]
@smellems Good morning. I have a word doc that contains all of the info I wanted to submit to the ORE. Can I send it to you via email? If so, can you pass me your preferred address? Thanks.

**Comment by smellems** [comment]
@jethiercrc you can send it here: sebastien.lemay@hrsdc-rhdcc.gc.ca I will add it

**Comment by jethiercrc** [comment]
Thanks Sebastien. I sent you an email earlier in the week with the details. Let me know if there's anything else for me to do. Thanks.

**Comment by smellems** [comment]
@jethiercrc sorry I didn't get your email.  It should work, since I did get one from someone else asking to add some Software :smiley:

**Comment by jethiercrc** [comment]
Thanks for letting me know. I just sent it again at 12:25pm.
