### ISSUE TITLE
CanadaBot forking across projects

### ISSUE THREAD

**Issue by j-rewerts** [canada-ca/ore-ero#171]
I've created [an issue](https://github.com/PRB0t/PRB0t/issues/45) upstream to get their thoughts on this.

From the issue:
>I'd like to understand PRB0t's behaviour with respect to forks a little better. After playing around a little bit, my team and I were able to make a bit of a mess using PRB0t. Check out this PR. Unfortunately, I deleted the repo that the PR is based on, so we can't look at it anymore 😢

>When I was originally working on PRB0t (CanadaBot in our case), I forked the repo from a fork of ore-ero. The graph looks like:

>canada-ca/ore-ero > VilleDeMontreal/ore-ero > canada-bit/ore-ero

>I then used CanadaBot to submit a PR to canada-ca/ore-ero.

>What does the community think is the best way for PRB0t to handle these types of situations? Should it be deleting it's fork every single time and then reforking? Should it just attempt to sync its fork with the upstream?

**Comment by j-rewerts** [comment]
I'll keep an eye on this issue @BassamAjam. Right now, I don't have the perfect solution. I think a good short term fix is to just ensure that the upstream for CanadaBots fork is canada-ca/ore-ero, which is easy to do.

**Comment by smellems** [comment]
How does it work?  Our instance of PRBot (Canada-bot) has a clone of the repo.  But it's never updated.

**Comment by j-rewerts** [comment]
It's a little weird, but CanadaBot submits a PR to its fork from the master of the upstream, then it merges it. This is meant to occur every time, but the way the error handling is done, I think it can fail half way through, without updating the forks master. 

I've [opened an issue](https://github.com/PRB0t/PRB0t/issues/46) to track this.

**Comment by j-rewerts** [comment]
I've spoken with the creator of PRB0t regarding this issue. He is totally aware of it and open to solutions. I think in the near term, we can probably just deal with it, but longer term we have several options, which I'll post in the previously mentioned issue.

**Comment by j-rewerts** [comment]
I've fixed this in [CanadaBot](https://github.com/canada-ca/canada-bot). Forks are deleted after every pull request is submitted.
