### ISSUE TITLE
FileWriter does not allow for creation of files

### ISSUE THREAD

**Issue by WJXHenry** [canada-ca/ore-ero#173]
The *FileWriter* class in [`git-file-manager.js`](https://github.com/canada-ca/ore-ero/blob/3c0674f1f65c8032d8473fc8b473e4f49ef240e2/assets/js/src/git-file-manager.js#L4-L48) currently does not allow the creation of new files in the *ore-ero* repo. It seems that pull requests can only be created for existing files.

This is problematic when a user wants to submit a new project with an administration code whose .yml file is not currently in the *ore-ero* repo. Reference to code:

https://github.com/canada-ca/ore-ero/blob/3c0674f1f65c8032d8473fc8b473e4f49ef240e2/assets/js/src/index.js#L89-L125

The *FileWriter* class will throw a *404 (Not Found)* error when its `get` method is called, and PRB0t will be unable to create a pull request for the non-existent file and throw an *Internal  Server Error*.

**Comment by j-rewerts** [comment]
I didn't know about the code quote you just did! That's so cool!

I had tested this when I was working on it and it seemed to work. The code you quoted is designed for exactly the situation you described. I'll take a look at this.

In terms of design, I'm wondering if there's a better way for me to handle this. I don't love handling the 404 externally. 

What if we did this: 
1. Create a POJO that has the exact schema of the code.yml file. 
2. Load the code file on GitHub. If it doesn't exist, use an empty object.
3. Merge the object from 1 and 2, ensuring releases has the current custom merge applied.

This would make things easier and more robust I think.

**Comment by WJXHenry** [comment]
The changes you described seem good to me.

**Comment by smellems** [comment]
Not sure if this could help, but the [code template file](https://github.com/canada-ca/ore-ero/blob/master/_data_templates/code_mandatory.yml) could be used as a base file.

**Comment by j-rewerts** [comment]
This is no longer an issue.
