### ISSUE TITLE
Build: Code Contact Name (en-fr)

### ISSUE THREAD

**Issue by j-rewerts** [canada-ca/ore-ero#175]
We currently have name.en and name.fr in the schema for code. 

https://github.com/canada-ca/ore-ero/blob/3c0674f1f65c8032d8473fc8b473e4f49ef240e2/_data/schemaCode.yaml#L6-L13

Is it common to have an English name and a French name? 

If we want to keep this, I'll add the field to the form. If we want to remove it, I'll update the schema and the associated files.

**Comment by j-rewerts** [comment]
@imadeDev Maybe you can help me out here?

**Comment by smellems** [comment]
Right!  The Name for the contact should not have the `en` and `fr`.

Schema is good!
https://canada-ca.github.io/ore-ero/en/open-source-code-schema.html

**Comment by smellems** [comment]
Same issue for contact name in the schema for OSS

https://github.com/canada-ca/ore-ero/blob/18cd8a36c01495b24b016af3ba3d18aaf1dee509/_data/schemaOss.yaml#L28-L35

**Comment by WJXHenry** [comment]
@smellems @j-rewerts I'll be happy to take on this issue

**Comment by imadeDev** [comment]
> @smellems @j-rewerts I'll be happy to take on this issue

Its Done :)
