### ISSUE TITLE
Selecting 'Administration code' in the Open Source Code Form resets current field inputs

### ISSUE THREAD

**Issue by WJXHenry** [canada-ca/ore-ero#177]
If the user has filled out the other fields in the Open Source Code Form and decides to fill in the *Administration code* field, the current fields are reset and the input values lost.

**Comment by BassamAjam** [comment]
@smellems @WJXHenry  I can fix it.
We can also add a reset button for the form if you think it does matter

**Comment by fredericlestage-vdm** [comment]
Seems to be caused by the code on _includes/footer.html - line 250
