### ISSUE TITLE
Formatting issue on code.open.canada.ca using MS Edge

### ISSUE THREAD

**Issue by gc-ianbell** [canada-ca/ore-ero#1777]
Hello, there is a formatting issues on this page: https://code.open.canada.ca/en/index.html

![image](https://github.com/canada-ca/ore-ero/assets/69003550/7a08dc4a-c683-4dea-adc2-8396e8e1da8f)

The Open Source Code block is the only thing misaligned on the page. This was observed using MS Edge Version 115.0.1901.203 and Firefox 114.0.2 on Win10 21H2

**Comment by smellems** [comment]
Thanks for creating an issues for this.  I will look into it
