### ISSUE TITLE
French pages not updating with latest changes

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#1952]
Changes from #1948 (crc-covlib) have not been updated on the ORE Website when using the French URL (ouvert).
https://code.ouvert.canada.ca/en/open-source-codes.html

Is Github Pages still updating for the French Repo?  Or maybe just need to restart the build.
https://github.com/canada-ca/ore-ero-fr

The syncs are working and the update is in the code, but the French site is not updated.

**Comment by nschonni** [comment]
I think it's related to the deprecation of the GitHub Pages build setup. Might need an explicit build action now. I'll take a look
