### ISSUE TITLE
What's it for?

### ISSUE THREAD

**Issue by jkshapiro** [canada-ca/ore-ero#20]
It would be useful to have a sentence or two on the page explaining what the purpose is of collecting this information. What use cases does it serve?

What are the scope lines? Why does it include all Canadian governments and only them? What about crown corporations and other publicly regulated bodies e.g. universities?

Does it include any software used on the job by any individual in the public service? What about consultants and other service providers?

Do we include software that depends on other software, e.g. browser plugins?

Which licences count as open source for this purpose? Why?

What's the maintenance plan? Who's responsible for keeping the information current?

**Comment by gcharest** [comment]
Hi @jkshapiro !

Thanks for the feedback. The Open Resource Exchange is in its nascent form and we're still working on the final form it will be taking from an architecture point of view.

Actual context is definitely needed and we'll try to provide some more as soon as possible.

For now, I'd say that the initiative was quickly put together to try and capture our internal projects that are being shared publicly as open source. The second part was to identify all the open source software (e.g.: Drupal, Firefox, etc.) that we currently use within the Government of Canada.

> What use cases does it serve?
I would see two main use case at this point with a possible third one:

1. I'm looking for all the "internal" Open Source Software projects the Government of Canada has released the code and where they are hosted.
2. I'm looking for all the "external" Open Source Software projects the Government of Canada is using as part of its building blocks and/or contributing back to.
3. I'm looking for all APIs available from the Government Canada. (This part 

I think we would see this tool as a go to place for public servants as well as general public to have a single point to go to for Open Source projects either from the government or used by the government. It should be accessible through the Open Government Portal (https://open.canada.ca/en).

> What are the scope lines? Why does it include all Canadian governments and only them? What about crown corporations and other publicly regulated bodies e.g. universities?

We want to start small and build it up. We're relying on our internal community to drive the content of this repository. At this point, the idea is to reuse what we've been doing internally and make sure that we're not doing the same thing more than once. It would be better for the Government as we can expedite the development of solutions in support of our citizens but it would also cut down costs so it would have another advantage for the population.

> Does it include any software used on the job by any individual in the public service? What about consultants and other service providers?

That's a good question. At this point, we're really looking at what is internally "approved" if you will. What consultants may use to provide us with a deliverable (presentation, document, etc.) is not necessarily of interest for this exercise but could be part of a future effort if needed.

> Do we include software that depends on other software, e.g. browser plugins?

Yes, any open source software such as plugins, add-on or even platforms could be of interest here. There are different dimensions to look at this: re-usability of the software across departments, ways of configuring them, lessons learned but also security evaluations. In the end, if a department has assessed an open source software, knowing who to contact would expedite the reuse of the solution. There's a lot of potential in sharing.

> Which licences count as open source for this purpose? Why?

This is an interesting question that we will need to study further with our lawyers. But at this point, my team and I would most likely refer to list that can be found on the Open Source Initiative (https://opensource.org/licenses) as well as the Open Government Licence (https://open.canada.ca/en/open-government-licence-canada) if someone was to release software under it.

> What's the maintenance plan? Who's responsible for keeping the information current?

Another very good question. This is a prototype, a quick voluntary aggregation of the information that was provided to us. We need to figure out a proper governance on the data that fits in this repository and a process that does not add pressure to the already busy IT folks in all our departments. There are means in place that could be leveraged to somewhat automate the production of this information but we do need to work that part out as well.

Hope this helps. There's a lot of work needed in this space but we have passionate employees and community members providing feedback, ideas and recommendations! Please continue asking questions!

**Comment by MaryBethBaker** [comment]
Parts of this read like a new section to you readme file...

**Comment by gcharest** [comment]
Probably will clean it up and add it! Thanks for suggesting ;)
