### ISSUE TITLE
Improvement on the tags field in the forms

### ISSUE THREAD

**Issue by fredericlestage-vdm** [canada-ca/ore-ero#206]
I noted that the form validation doesn't work as expected for the tags field in the open source code form. My understanding is that since the fields are added dynamically when the user press the add more tags buttons, when the user tries to submit the form without having done so, the validation passes even if the field are empty.

Since they are mandatory, I think it would make sense to have a set of default field, and then the user could add more when required. I did some testing and that seems to resolve the validation issue

**Comment by fredericlestage-vdm** [comment]
Would it be a good idea to do so, or is there a reason why the fields aren't there by default?

**Comment by smellems** [comment]
Thanks for fixing this!
