### ISSUE TITLE
Page 2 & 3 link problems

### ISSUE THREAD

**Issue by mgifford** [canada-ca/ore-ero#22]
Page one works fine, but 2 & 3 don't give you more details when you click on the link:
https://canada-ca.github.io/ore-ero/open-source-software.html#mediawiki

This is what I get on the first page:
<img width="700" alt="screen shot 2018-07-13 at 8 12 53 am" src="https://user-images.githubusercontent.com/116832/42691079-accf238a-8674-11e8-84a0-3231f913cdd9.png">

Tested in Chrome & FF on a Mac.

**Comment by smellems** [comment]
@mgifford Thank for creating this issue!  I had seen this bug before but it seemed inconsistent..

I noticed that the entries that did not work were the ones that we sorted to page 2 or more event if you re-sort the table by different columns.  I disabled the paging and it fixed the problem with the light box not showing.  Maybe it a problem with WET or Datatables

**Comment by smellems** [comment]
We should investigate this issue because when we start adding more open source code projects we are going to need to enable paging.

**Comment by smellems** [comment]
@imadeDev found that using a "Middle screen overlay" instead of a "Centred popup" (Lightbox) fixes the problem.  #80
