### ISSUE TITLE
YAML linting and formating

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#221]
The current YAML format was linted using the following service and follows it's conventions
http://www.yamllint.com/

When PRBot submits a change it's rewriting the whole file in a different format and that makes it hard to see what changes were made to the files.

Possible solutions:
- Re-lint the YAML before sending it through PRBot
- Update current YAML files to match format used by PRBot

**Comment by imadeDev** [comment]
Hi, we can use a linter for YAML files. I found this script:  https://github.com/adrienverge/yamllint,, we can writing a custom configuration file with our rules , https://yamllint.readthedocs.io/
I created a PR that shows how we can use this script, Add linter for YAML files #234. https://github.com/canada-ca/ore-ero/pull/234

**Comment by j-rewerts** [comment]
@smellems I'll also work to see if I can figure out how to change the formatting of the YAML writer. I can't seem to find a good browser-supporting YAML parsing library. The one I've got has bare bones documentation. I'll dig deeper and work with @WJXHenry to get this resolved.

**Comment by smellems** [comment]
YamlLint was added to the build.  Not sure if it could also reformat the YAML.. but I guess reformatting (linting) would have to be done by CanadaBot

**Comment by smellems** [comment]
YAML formatting was updated for all files but it still does not match when an update is submitted using the form.

I only updated my email in #523

**Comment by fredericlestage-vdm** [comment]
My latest pull request should take care of this. @imadeDev and I went through all the files to adapt them to how jsyaml format files, so when it's merged, this should be resolved. There's also different format we can pass to the jsyaml object config (when using the dump method), but I think it's safer to use the default version and adapt around it than the other way around.

**Comment by fredericlestage-vdm** [comment]
Additionally, @j-rewerts mentionned that if it happens again, it might come from a known issue of PRB0T when it's not updated its own fork, creating a divergence between the pull request and master. One workaround is to manually delete PRB0T forked repo, so it force it to refork from master and not use its current outdated version.

There's two issues regarding this:
https://github.com/PRB0t/PRB0t/issues/45
https://github.com/PRB0t/PRB0t/issues/25

But otherwise it shouldn't be an issue anymore
