### ISSUE TITLE
Auto-fill feature in OSC form does not work in some browsers

### ISSUE THREAD

**Issue by WJXHenry** [canada-ca/ore-ero#251]
The auto-fill function for when an existing project is selected does not seem to work for MS Edge (or IE). It works well for Firefox and Chrome browsers.

I'm using MS Edge 42.17134.1.0.

| MS Edge | Chrome |
| ---------- | ---------- |
| ![ms_edge](https://user-images.githubusercontent.com/30060214/58584820-6b242b00-8214-11e9-8c25-71db848dc3cd.gif) | ![chrome](https://user-images.githubusercontent.com/30060214/58585007-d0781c00-8214-11e9-8389-3aaaea65dfe6.gif) |

**Comment by fredericlestage-vdm** [comment]
Are we even supporting IE? As for edge, I tested this morning with the dev edition for Edge (I'm on w7 so it was the easiest(only?) way of getting Edge) and it seems to work. We did change a lot of things on how the form works, I suppose this new version works in a different way that doesn't cause the issue.

@WJXHenry Could you test again with Edge, just to make sure it does work with an actual version of Edge and not just the dev edition I used. And if it works, we can close this issue.

This is the version I'm using: Version 77.0.211.3 (Official build) dev (64-bit)

**Comment by WJXHenry** [comment]
@fredericlestage-vdm I just tested it in MS Edge and it works fine! I'll close this issue
