### ISSUE TITLE
Question: How restrictive should the project name fields be in OSC form?

### ISSUE THREAD

**Issue by WJXHenry** [canada-ca/ore-ero#252]
Here is the mentioned field
![image](https://user-images.githubusercontent.com/30060214/58585926-28b01d80-8217-11e9-97a1-9670e737e56e.png)

Some existing project names do not pass the existing form validation
![image](https://user-images.githubusercontent.com/30060214/58586104-92c8c280-8217-11e9-911f-3d4d80bc8786.png)

**Comment by j-rewerts** [comment]
I feel like punctuation should be allowed.

**Comment by smellems** [comment]
I think this is now working
