### ISSUE TITLE
Accessing nested fields

### ISSUE THREAD

**Issue by j-rewerts** [canada-ca/ore-ero#272]
One of the gross things I did was add `_en` or `_fr` to the end of every multilingual field. The reason for this was because I couldn't get certain widgets to work on nested fields for some reason. 

Here are a few examples [[1](https://github.com/j-rewerts/ore-ero/blob/master/admin/config.yml#L13), [2](https://github.com/j-rewerts/ore-ero/blob/master/admin/config.yml#L29), [3](https://github.com/j-rewerts/ore-ero/blob/master/admin/config.yml#L31)]

I'm pretty sure this is just due to my lack of experience with Netlify. This has got to be possible. @WJXHenry If you can figure this out, that'd be awesome!

**Comment by fredericlestage-vdm** [comment]
Using lists might be what we're looking for https://www.netlifycms.org/docs/widgets/#list

I'm working on a demo branch to see how it works.

**Comment by fredericlestage-vdm** [comment]
@WJXHenry Are you working on this or should I go through with what I found?

**Comment by WJXHenry** [comment]
Hey @fredericlestage-vdm, I haven't been able to find an existing solution to this issue so go right ahead! However, I think the main problem isn't the creation of the structure to be:

```yaml
name:
  en: "English Name"
  fr: "French Name"
```

but in referencing the nested structure when using a widget like [Relation Widget](https://www.netlifycms.org/docs/widgets/#relation). I found that the [Object Widget](https://www.netlifycms.org/docs/widgets/#object) was also able to create a YAML file with that structure.

I opened an [issue](https://github.com/netlify/netlify-cms/issues/2356) in Netlify requesting nested field options as a feature.

Please share your thoughts on this and any solution you came up with for this issue! 😄

**Comment by fredericlestage-vdm** [comment]
I see what you mean. I'm actually able to output the object (for instance name), but not a particular value within it (for instance name.en).

This is as far as I've gotten:
![showingObjectAsMap_butNoOutputOfNestedField](https://user-images.githubusercontent.com/50632796/59116851-749b4a80-891a-11e9-8342-3705649d6987.png)

But I'll continue to investigate
