### ISSUE TITLE
Allow anonymous contributions

### ISSUE THREAD

**Issue by j-rewerts** [canada-ca/ore-ero#274]
Netlify forces users to log in with their GitHub accounts. One of our requirements we solved with PRB0t was to submit a pull request on behalf of anonymous users. I believe it's possible to add this functionality to Netlify, though it would be a fairly major undertaking.

Here's how I think it could work:
1. Set up a custom authentication backend ([our current one is here](https://dashboard.heroku.com/apps/ore-ero-auth))
1. Setup a bot GitHub account (CanadaBot)
1. Ensure the bot doesn't have write access to ORE-ERO
1. When users access the dashboard, automatically authenticate them as CanadaBot (we own the auth service, so we can do this easily)
1. Editorial workflow:

At this point, we run into a problem: CanadaBot can't write to ORE-ERO, which is good for security, but bad for actually giving people the ability to anonymously edit our data files. I suggest we add a new [publish mode](https://www.netlifycms.org/docs/configuration-options/#publish-mode) to Netlify. Currently, [we're using](https://github.com/j-rewerts/ore-ero/blob/master/admin/config.yml#L7) `editorial_workflow`, but maybe we could make a new one that makes the submission from a fork, rather than from a branch in the repo. This would mean Netlify could support 2 admin user types: maintainers and collaborators, just like GitHub.

**Comment by j-rewerts** [comment]
Currently, users that don't have write access to the repo get this message:
![Clipboard - June 5, 2019 1_16 PM](https://user-images.githubusercontent.com/8295080/58976445-b3979780-8784-11e9-8843-e3e23b41ec4a.png)

Thanks for this @BassamAjam!

**Comment by fredericlestage-vdm** [comment]
Check https://www.netlifycms.org/docs/add-to-your-site/#enable-identity-and-git-gateway

It seems we can either create accounts or leave the admin panel completely open to anyone. I suppose it could work in conjunction with the other changes proposed (using PRB0T or another workflow with forks)

**Comment by j-rewerts** [comment]
Amazingly, work started on [this](https://github.com/netlify/netlify-cms/issues/2096) today 🤣 

Lucky us!

They have a really great writeup in there about this issue that has thought of a bunch of problems I hadn't.
