### ISSUE TITLE
Add HTML-Proofer to Travis build

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#47]
https://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by smellems** [comment]
Is it better?  We'll look into it.  I'd like it if we don't have to add a package.json and lock and just keep it in the Gemfile and .travis files.

**Comment by nschonni** [comment]
> Is it better

I believe so, because it is maintained by the w3c


> I'd like it if we don't have to add a package.json and lock

That usually isn't a good idea, because then version bumps might cause CI to start failing

**Comment by smellems** [comment]
W3C :+1: 

I meant not adding Node packages and just using Ruby gems. Trying to keep it simple.  We'll see what works better

**Comment by gcharest** [comment]
Let's add accessibility as well, like Lighthouse
