### ISSUE TITLE
Name conflicts

### ISSUE THREAD

**Issue by fredericlestage-vdm** [canada-ca/ore-ero#615]
We should find a way to handle when a user attempts to create a new administration, code, software or standard with the same name of one that already exists. As of now, all the new info from the form will overwrite the existing data, which is bad.

My current ideas are:
- Check if WET-BOEW already has a way to handle that
- Add our own custom validation (onChange, check if value exists)
- Throw an error in the JS workflow when we encounter such an error

Thoughts?

**Comment by smellems** [comment]
We should check for this and show an error before the form can be submitted

**Comment by fredericlestage-vdm** [comment]
I'd suggest then that we validate the name onChange just so the user doesn't go through the whole process of filing the form and then get denied
