### ISSUE TITLE
Coherence of status

### ISSUE THREAD

**Issue by fredericlestage-vdm** [canada-ca/ore-ero#618]
The list of available status for code project sometimes doesn't include the status of some of the data we have. For instance, Devex, from the province of Alberta has its status set to Production, which is not one of the valid value we defined for status (Alpha, Beta, Maintained, Deprecated or Retired)

**Comment by smellems** [comment]
It would be great if validation could catch this.

We need to fix existing data to align with the defined status values

**Comment by fredericlestage-vdm** [comment]
Resolved in #616
