### ISSUE TITLE
Page file names - Open Standards

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#686]
I noticed, that with the latest changes, the open-standard pages file names and permalinks were updated to open-source-standards.

This is confusing since, as discussed, "open standards" are not standards on open source.  They are for file formats and protocols that are developed in the open, often by a standards setting org (W3C, ISO, OASIS, ..) and where the technical specification is available at no cost.

I suggest we rename the open standard files here
https://github.com/canada-ca/ore-ero/tree/master/_pages/en

- open-source-standard-form.html -> open-standard-form.html
- open-source-standard-schema.html -> open-standard-schema.html
- open-source-standards.html -> open-standards.html

The French file names were not changed in this way and are correct: "normes ouvertes".

**Comment by fredericlestage-vdm** [comment]
It was a mistake on my part, I wanted to have a better consistency on file names and URLs. I'll change them back
