### ISSUE TITLE
Yamale Version 2.0

### ISSUE THREAD

**Issue by fredericlestage-vdm** [canada-ca/ore-ero#702]
The new version of yamale (2.0, updated on 19/08/2019) causes the schema validation to fail regarding the required=False instruction.

Last version to work: 1.10.1

**Comment by fredericlestage-vdm** [comment]
Temporary fix: #703

**Comment by smellems** [comment]
Can we reproduce the bug and open an issue on https://github.com/23andMe/Yamale

**Comment by mildebrandt** [comment]
Hello, thank you for using Yamale! In 2.0 there has been a change in how the parent behaves when all the children are optional. There's a short outline in the release notes: https://github.com/23andMe/Yamale/releases/tag/2.0

We always suggest pinning requirements to the current major number to avoid surprises. Yamale will follow the semantic versioning model outlined here: https://semver.org/

I've outlined an example yaml that I think should validate correctly in the referenced issue: https://github.com/23andMe/Yamale/issues/65

There is another bug related to this, but I feel that yaml should pass validation. Can you please take a look to see if that correctly describes your case? If it doesn't, please provide a schema and yaml document that you feel should validate successfully but actually doesn't. 

Thanks!

**Comment by smellems** [comment]
@mildebrandt Thanks!  I need to test this and will let you know

**Comment by smellems** [comment]
@mildebrandt I looked into it this morning and fixed our issue by updating the schema to make the parents optional.  The validation should now pass using Yamale 2.0
