### ISSUE TITLE
Displaying projects when no data in the current language

### ISSUE THREAD

**Issue by fredericlestage-vdm** [canada-ca/ore-ero#706]
As of now, we removed the obligation for users to fill the form in both languages, they can fill only one. However, that creates an issue when we want to display the informations of the new data (in the table for instance).

What should be the behaviour? Here's a few ideas:
- Copy each blank fields in the data with the same values as the other lang
- Simply not displaying a project if there's no data in the current language
- Displaying the other language but with a note saying data not available in french/english
  - Or displaying an excerpt of the project (for instance only the name) in the other language and adding a note about data not being available in the current language
  - And adding the option to see it anyway in the other language
- Adding a note at the end of the table saying X amount of project not displayed because the data is not available in the current language

**Comment by smellems** [comment]
It would have been better to leave both languages mandatory until we have the solution to do translations.  Can we do that?  Having both official languages is very important.

At worse we could use the mandatory language to fill in the blank.
