### ISSUE TITLE
Define and document list of status

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#73]
For the status feild, we should define a list of common vocabulary we could use and then have translations for the form and schema documentation.

Examples
- Alpha
- Beta
- 1.0
- Production

Does Production make sense?  I know some of the data already uses it

**Comment by nschonni** [comment]
"Production" might be fine, if you drop the "1.0"
Although if you're talking about the status, maybe:
- alpha
- beta
- maintained
- deprecated
- retired

There are some discussion around package status' over on https://github.com/nodejs/package-maintenance/

**Comment by gcharest** [comment]
I'd recommend this as well. Production really speaks as to the version of
the instance you're running IMHO, no matter which version the project is
maintaining.

Le lun. 25 févr. 2019 16 h 02, Nick Schonning <notifications@github.com> a
écrit :
