### ISSUE TITLE
Add more information to lightboxes

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#766]
The lightboxes for Software and Standards are almost empty when compared with the Code.

It would be good to display most of the information we have in the datasets.  Especially contact information and links.  The partners are also not displayed anywhere for Code.

- [ ] Add information for Softwares
- [ ] Add information for Standards
- [ ] Add partner information to Code

**Comment by Tommyhudon** [comment]
For open standards we could add "started using" and "reference name URL" as an hyperlink in the lightbox

**Comment by smellems** [comment]
@Tommyhudon yes that would be good!
