### ISSUE TITLE
A Page on Metrics

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/ore-ero#797]
Data is the best tool we have to enable folks - a page that provided analytics on the # of projects each Crown Institution has, as well as the Programming Languages they work in, and any other data folks might think is relevant - but being able to explicity point to executives and say "Really - are you sure you're enabling your staff to work in the Open? Cause - we only found 3 projects for your Organization". would be a massive boon.

**Comment by smellems** [comment]
As you probably know, you can currently filter to see only Federal public administrations for all sections (code, software and standards).  You can also filter of sort by department - https://canada-ca.github.io/ore-ero/en/open-source-codes.html

But it doesn't show exactly what you are looking for.  I think a good option would be to improve the layout/display of the [List of repositories per public administration](https://canada-ca.github.io/ore-ero/en/open-source-code-groups.html) page.  Currently it shows Groups (on Github, Gitlab, ..) and what departments have repos (projects) there.  We could add the number of projects beside the name of the department.

Another option is just to use the JSON data to make some kind of dashboard that shows departments and their open projects.  All the data for the ORE is made available as JSON

- https://canada-ca.github.io/ore-ero/code.json
- https://canada-ca.github.io/ore-ero/software.json
- https://canada-ca.github.io/ore-ero/standard.json
- https://canada-ca.github.io/ore-ero/administrations.json

**Comment by ShadeWyrm** [comment]
Oh perfect, if I have time I'll build a dashboard off those json items and pull request it in. 

If I don't - well someone can beat me to the punch! :D
