### ISSUE TITLE
Add Known Environment Canada Open Source Software

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/ore-ero#811]
Environment Canada Developed a Wiki Entry showing what OSS it had available.

https://www.gcpedia.gc.ca/wiki/Environment_Canada_Use_of_Open_Source_Software

**Comment by gnewton** [comment]
My understanding is that web URL is only be available to internal to GoC users.

I would suggest a general policy of avoiding links on github (and other public source code management platforms) that point to internal-only GoC resources.

**Comment by ShadeWyrm** [comment]
Did a pass on what I was comfortable adding.
