### ISSUE TITLE
View jumps or refreshes as soon as it loads

### ISSUE THREAD

**Issue by CwithaK** [canada-ca/ore-ero#813]
When I view this page https://canada-ca.github.io/ore-ero/en/open-source-codes.html the view refreshes almost immediately but I can see the columns were ordered differently previously an that method is flashed by each time it loads.  I had previously looked up Montreal - and see City of Montreal as the content of the first column - but for only 1/2 a second.

**Comment by Tommyhudon** [comment]
It seems there is not enough space for the whole table to show. When the webpage loads, we see all the columns for 1/2 second before they disapear to fit the webpage's layout. Hence, either we remove these columns  that we see for 1/2 second or we change the layout of the webpage to show all columns.

**Comment by smellems** [comment]
The columns are hidden on page load so they don't take up too much space but will still be searchable by the filter.  It's also ordered by name.
