### ISSUE TITLE
Can't update project information without providing a new Canadian public administration

### ISSUE THREAD

**Issue by nschonni** [canada-ca/ore-ero#818]
When selecting an existing project to update licence/tag information, because the Administration fields are required, the form can't be submitted.
I'm thinking that adding an administration might be something people want when updating a project, but maybe just have the heading with the "+" buton so other updates are possible

**Comment by Tommyhudon** [comment]
If you want to update an existing project without adding a new administration, you need to select an administration that is already on the project. It won't duplicate the administration. 
We could replace the ''Administration field'' by an  "add a new administration for this project" button when updating so it's less confusing.

**Comment by simon332114** [comment]
Isn't this already solved?
![Screenshot from 2020-02-20 10-54-58](https://user-images.githubusercontent.com/46785151/74953284-7b49ef00-53cf-11ea-90b2-211a622dd295.png)

**Comment by nschonni** [comment]
@simon332114 that's actually showing the issue here. I'll give a better set of reproduction steps here.

Current flow:
1. Go to the Software Form https://canada-ca.github.io/ore-ero/en/open-source-software-form.html
1. Select an existing project from "If you wish to update information of a software that already exists in our library, please select it below"
1. Update a value like the French description. 
1. Error is show that "Error 1: Canadian public administration - This field is required."

Expected flow:
1. Make edits like 1-3 above
1. No error messages

**Comment by simon332114** [comment]
Then the most simple fix would probably be to make it so the administration related fields aren't required when a project/software that already exists is selected
