### ISSUE TITLE
Open standards lightbox not working when website is in french

### ISSUE THREAD

**Issue by Tommyhudon** [canada-ca/ore-ero#827]
If you go on "normes-ouvertes.html"and click on the"Représentation de la date et l'heure" standard, the lightbox won't show up.

**Comment by smellems** [comment]
Peut-être à cause de l'accent.

The id used is `représentation-de-la-date-et-de-l-heure` maybe it does not work with the lightbox

**Comment by Tommyhudon** [comment]
You were right, the accent is the problem.

**Comment by smellems** [comment]
This bug is site wide.  We should look at using `slugify: "latin"`

https://jekyllrb.com/docs/liquid/filters/
