### ISSUE TITLE
Build - URL on multiple lines in YAML have space in HTML

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#836]
Long URLs created by Canada-bot will be split on multiple lines in YAML.  This will leave space in the href value in HTML making the link not work

Example
https://github.com/canada-ca/ore-ero/blob/d276df0144591b343c76f8f247ca0fe3fd585da6/_data/standard/utf-8.yml#L52-L61

**Comment by ShadeWyrm** [comment]
Are we able to replicate the issue that caused this anymore?

**Comment by simon332114** [comment]
The exact url used here doesn't cause that problem anymore, and a fake long url didn't cause any issue either
