### ISSUE TITLE
New area - "Dependencies"

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/ore-ero#840]
Essentially, a new section to provide details on all the Dependencies the Crown Institutions have for their projects.

Ex: https://code.etalab.gouv.fr/en/deps/diverse-project

Ideally we'd have the ability to have dependencies listed as part of individual projects, and a section that provides the full list of Dependencies the various institutions are using so that we can provide the list for areas that we should spend time and resources in.

**Comment by simon332114** [comment]
I tried looking at the example provided but it doesn't seem to show any dependencies and the thing they claim to use to find dependencies (https://backyourstack.com/) isn't really working. I'm assuming this is essentially making a script that goes through package-lock.json/gemfile.lock/.gitmodules/whatever equivalent they may have for every project and making a page to display it?
