### ISSUE TITLE
Remove columns from DataTables to avoid overflows

### ISSUE THREAD

**Issue by gcharest** [canada-ca/ore-ero#86]
![image](https://user-images.githubusercontent.com/1690085/53988808-5a22bc80-40f2-11e9-9da4-bb628df74793.png)
The table overflows the center of the page.

**Comment by gcharest** [comment]
Linked to PR #80

**Comment by smellems** [comment]
The tables were already overflowing before switching the lightboxes.

I think the fix would be to hide the Administration column for Open Source Code.  Hide the Homepage on the Open Source Software page.

**Comment by gcharest** [comment]
Ha! I hadn't noticed... Probably needs to be fixed either way 😄

**Comment by gcharest** [comment]
So, not linked to #80 ...
