### ISSUE TITLE
Email Validation 

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/ore-ero#908]
Add a Validation pattern requiring an email associated with an organization. 

EG: updates to add information on a Federal Org require a @canada.ca or equiv email. (@TBS-sct.gc.ca etc...)

**Comment by nschonni** [comment]
There is https://github.com/benbalter/gman, but I'm not sure how much it covers at the municipal level

**Comment by fnduister** [comment]
> There is https://github.com/benbalter/gman, but I'm not sure how much it covers at the municipal level

It really only checks the suffixes, but from what I understand we would also need to check the extension of the email (EG: TBS-sct) , but do we have this information for each administration?

Also do we require an email for the already created organizations? do we keep track of the emails for each modification (and timestamp I suppose) or is it only a reference email?

**Comment by nschonni** [comment]
Because the email address is a freeform, we can only really just do a basic check that they're using a gov address. It looks like it does have decent list for municipalities though https://github.com/benbalter/gman/blob/master/config/domains.txt

**Comment by fnduister** [comment]
After some research, I don't see how we could use that library with the jekyll right now, @nschonni do you have suggestion on how to implement that?

**Comment by ShadeWyrm** [comment]
I would just go the route of adding a new optional field to the administrations yml that defines the email.

Eg:
```
- code: aafc-aac
  name:
    en: Agriculture and Agri-Food Canada
    fr: Agriculture et Agroalimentaire Canada
    email_suffix: @canada.ca
```

Anything larger then that will just be overkill I think, and I don't really want to rely on a list that contains other countries emails.
