### ISSUE TITLE
Define process for Creating, Reading and Updating (code) using the form

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#95]
How does the form work?
Can it get existing data to modify it?  How do you search existing data?
Need Github account to create a Pull request
How do I create a Administration if it's not there?
...

**Comment by BassamAjam** [comment]
I found a project on Github that uses a library called GitHub.js. The existing code in the project allows to choose a local file on our computers, to upload it in github repo and to write a commit.
The code needs the following informations to work:
-GitHub username
-password or authentication token if two-factor authenetication is enabled
-repository name
-branchName

N.B. : - If the choosen file already exists in the github repository, the file will be updated.
         - With the existing code, we can't choose a specific folder in the repository. 

However, there are other functions in the library that are not used in the code, for example: create a pull request, move a file, create a repo etc..

repo link:   https://github.com/AurelioDeRosa/upload-files-github.js
blog link:   https://www.audero.it/blog/2015/10/17/upload-files-on-github-using-github-js/

**Comment by BassamAjam** [comment]
-How does the form work?
I think we need to add a new section about the GitHub account informations of the users.

-Can it get existing data to modify it? How do you search existing data?
The informations will be overwritten. I think If there are modifications, the user must fill the entire form again.

**Comment by j-rewerts** [comment]
Is the goal with this to have the submitter authenticated? Maybe we could just submit the PR anonymously?

**Comment by gcharest** [comment]
I'd support Sébastien comment around interoperability here.

But the submitter should be authenticated to the service where the ORE is
hosted IMHO.

Le ven. 5 avr. 2019 13 h 05, Jared Rewerts <notifications@github.com> a
écrit :

**Comment by j-rewerts** [comment]
The challenge is that pull requests aren't part of Git, they're part of GitHub. For example, GitLab actually calls them [Merge Requests](https://docs.gitlab.com/ee/user/project/merge_requests/). If we want to review submissions prior to them being merged in, I think the only way to do that is using pull requests.

So I guess my next question is, do we want to review these form submissions prior to merge?

**Comment by j-rewerts** [comment]
@gcharest From what I can tell, we don't have any auth services set up yet. Is this something we'll be taking on soon?

**Comment by j-rewerts** [comment]
@gcharest @smellems @imadeDev I've got the ability to submit PRs from our site. Do we have an idea of what we'd like the PRs to look like? [Here](https://github.com/j-rewerts/ore-ero/pull/4) is an example PR I made. It uses the form:
Title: new project for {LOCALITY NAME}
Description:
Authored by {CONTACT EMAIL}
Project ***{PROJECT NAME}***
{PROJECT DESCRIPTION}

The form has more fields, but what would the team want to see when reviewing these? Also, should we  try to generate both French and English for the PR description?

**Comment by gcharest** [comment]
Having both languages should be needed before approving so I'd say yes.

For the other fields, what do you think @smellems?

Le lun. 8 avr. 2019 18 h 09, Jared Rewerts <notifications@github.com> a
écrit :

**Comment by smellems** [comment]
The form is the content of the actual pull request, making changes to _data files.

But we should ask for name and email of the person submitting the pull request (could be different than contact email in data being modified) and put that information in the pull request.  I would say, name, email and commit message.
This probably leaves us open to spam, since anyone can just submit pull requests.  I like the Canada bot!

We should require some kind of login. Maybe https://account.gccollab.ca/  Not sure if it possible to require to be logged in to use the bot and still be client side only.

Maybe captchas would be enough
