### ISSUE TITLE
Setup CNAME for code.open.canada.ca

### ISSUE THREAD

**Issue by nschonni** [canada-ca/ore-ero#988]
We've got preliminary 👍 from the open.canada.ca folks to move the site as a subdomain of open.canada.ca.
- [x] Setup CNAME for English subdomain `code.open.canada.ca`
- [x] Setup new repo to mirror content
- [ ] Setup CI to copy content with replaced CNAME of `code.ouvert.canada.ca`
- [x] Work through SSC process with open.canada.ca team

Still need to confirm with Cyber that the GitHub pages SSL is OK

**Comment by ShadeWyrm** [comment]
New Repo is available here : https://github.com/canada-ca/ore-ero-fr

**Comment by ShadeWyrm** [comment]
GitHub Pages SSL shows as okay, while it does specify some Cyphers that have been identified as "weak", they are still valid under the following Guidance.

https://www.cyber.gc.ca/en/guidance/guidance-securely-configuring-network-protocols-itsp40062

May wish to contact Github and ask them to remove them however to future proof and solve later problems.

**Comment by ShadeWyrm** [comment]
Request is in with SSC.

**Comment by ShadeWyrm** [comment]
Domains are live! Last step is ensuring the mirror between the two repos. :)
